refactor: Update CustomLinearCareTaskProgress
netreconlab/CareKitEssentials pull request #15
Opened 2024-07-10 18:27 UTC by luimillan3

changed the title of OCKEventAggregator.swift to CareTaskProgressStrategy+Math

removed struct CustomLinearCareTaskProgress
removed all appearances of CustomLinearCareTaskProgress to LinearCareTaskProgress

2024-07-10 18:51 UTC, cbaker6 commented
Thanks for working on this @luimillan3 can you add test cases for similar to https://github.com/netreconlab/CareKitEssentials/blob/094cf72f0b917b5558de17a14bd0a13c8c853bb4/Tests/CareKitEssentialsTests/OCKOutcomeExtensionsTests.swift#L7-L55

2024-07-10 19:04 UTC, cbaker6 commented
You can use something like the code below to make a dummy event:

```swift
let scheduleElement = OCKScheduleElement(start: Date(), end: nil, interval: DateComponents(day: 1))
        let schedule = OCKSchedule(composing: [scheduleElement])
        let task = OCKTask(id: "test", title: nil, carePlanUUID: nil, schedule: schedule)
        let value1 = OCKOutcomeValue(2)
        let value2 = OCKOutcomeValue(4)
        let outcome = OCKOutcome(taskUUID: task.uuid, taskOccurrenceIndex: 0, values: [value1, value2])
        guard let scheduleEvent = task.schedule.event(forOccurrenceIndex: 0) else {
            XCFail("Should have a schedule event")
            return
        }
        let event = OCKAnyEvent(task: task, outcome: outcome, scheduleEvent: scheduleEvent)
```

2024-07-13 00:05 UTC, cbaker6 requested changes
Looking great so far. I just provided some initial feedback.

Keep up the good work!

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        let outcomeValues = [OCKOutcomeValue(10),
These should be on a new line:

```swift
// Make the adjustments to all similar declarations
let outcomeValues = [
      OCKOutcomeValue(10),
      OCKOutcomeValue(15),
      ...
]
```

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    func testComputeProgressByAveragingOutcomeValues_MultipleOutcomesMultipleTargets() async throws {
Should be on newline

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    func testcomputeProgressByAveragingOutcomeValues_SingleOutcomeSingleTarget() async throws {
Should be on newline

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +final class CareTaskProgressStrategyTests: XCTestCase {
Should be on newline

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +private extension OCKAnyEvent {
Can you place this at the end of the file? The test should be at the top since it's the name of the file

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    func testComputeProgressByAveragingOutcomeValues_MultipleOutcomesMultipleTargets() async throws {
Remove underscores from the function names. The can be named something like:

```swift
func testProgressAveragingMultipleOutcomesMultipleTargets { ... }
```

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        let expectedValue = outcomeValues.map { $0.numberValue!.doubleValue }.reduce(0, +) / Double(outcomeValues.count)
no force unwrapping, see other comments

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    // test computeProgressByMedianOutcomeValues
You can remove all comments similar to this

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    func testComputeProgressByStreakOutcomeValues_SingleOutcomeSingleTarget() async throws {
Next line

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +    func testComputeProgressByStreakOutcomeValues_MultipleOutcomesMultipleTargets() async throws {
next line

2024-07-13 00:05 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/OCKOutcomeExtensionsTests.swift
> + gets the outcomeValues of the event, if there is no outcome values then we return an empty array
Remove all commented all code

2024-07-15 23:20 UTC, lmillan1 reviewed
Some minor style and formatting changes. Also removed all instance of force unwrapping to prevent potential crashes.

2024-07-15 23:39 UTC, cbaker6 requested changes
looks good, some nits

2024-07-15 23:39 UTC, cbaker6 commented on Sources/CareKitEssentials/Extensions/CareTaskProgressStrategy+Math.swift
> +    // swiftlint:disable:next line_length
add newline

2024-07-16 15:14 UTC, cbaker6 requested changes

2024-07-16 15:14 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        let expectedValue = outcomeValues.map { $0.numberValue?.doubleValue ?? 0.0 }.reduce(0, +) / Double(outcomeValues.count)
The extra casting shouldn't be needed, you can grab a `Double` value directly. Please make this change to all `$0.numberValue?.doubleValue`:

```suggestion
        let expectedValue = outcomeValues.map { $0.doubleValue ?? 0.0 }.reduce(0, +) / Double(outcomeValues.count)
```

2024-07-17 21:24 UTC, cbaker6 commented
@lmillan1 be sure to use GitHub to re-request me for review when this is ready

2024-07-17 22:08 UTC, cbaker6 requested changes
Looking good, some nits and suggestions

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        valueOfTen.kind = "myKind"
We want to reduce the possibility of programatic mistakes. Can you create two `String` variables at the top of the method and use them throughout?:

```swift
let kind = "myKind"
let kind2 = "otherKind"

var valueOfTen = OCKOutcomeValue(10.0)
valueOfTen.kind = kind
.
.
.
var valueOfThirty = OCKOutcomeValue(30.0)
valueOfThirty.kind = kind2
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            .computeProgressByAveragingOutcomeValues(for: event, kind: "myKind")
```suggestion
            .computeProgressByAveragingOutcomeValues(for: event, kind: kind)
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            .filter { $0.kind == "myKind" }
```suggestion
            .filter { $0.kind == kind }
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        valueOfTen.kind = "myKind"
Same with variable names for `kind`

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        XCTAssertEqual(progress.goal!, expectedGoal, accuracy: 0.0001)
```suggestion
        XCTAssertEqual(progress.goal, expectedGoal, accuracy: 0.0001)
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            )
This should be at the same level as the `l` in `let`

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            )
backspace

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        XCTAssertEqual(progress.goal!, expectedGoal, accuracy: 0.0001)
```suggestion
        XCTAssertEqual(progress.goal, expectedGoal, accuracy: 0.0001)
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        XCTAssertEqual(progress.goal!, expectedGoal, accuracy: 0.0001)
```suggestion
        XCTAssertEqual(progress.goal, expectedGoal, accuracy: 0.0001)
```

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            )
backspace

2024-07-17 22:08 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +            ]
backspace

2024-07-18 05:36 UTC, cbaker6 requested changes
Nits, be sure to look at the similar cod I didn’t comment on, those are done with the right amount of indenting

2024-07-18 05:36 UTC, cbaker6 commented on Sources/CareKitEssentials/Extensions/CareTaskProgressStrategy+Math.swift
> +        print("Progress \(progress)")
Be sure to remove all print statements

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Missing tab here and the next couple of lines

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Missing tab here and next few lines

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(15.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        let outcomeValues = [
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(15.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        let outcomeValues = [
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        valueOfTen,
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        valueOfTen,
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(20.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(15.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(20.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(10.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(10.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        taskUUID: UUID(),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(10.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        OCKOutcomeValue(15.0),
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        hour: 1,
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        id: taskUUID.uuidString,
Tab

2024-07-18 05:36 UTC, cbaker6 commented on Tests/CareKitEssentialsTests/CareTaskProgressStrategynTests.swift
> +        task: task,
Tab

2024-07-18 17:44 UTC, cbaker6 approved these changes
LGTM!

2024-07-18 17:52 UTC, cbaker6 approved these changes

2024-07-18 17:59 UTC, merged